# Config file of the PortalLock
#
#Permission:
#  portallock.ignore
#     
#
#
enable: true

messages:
  reload: '&aPortalLock configuration reloaded.'
  nopermission: '&cYou dont have permission.'
  denycreate: '&cNot allow create portals'